# Generated by Django 2.2.7 on 2021-04-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, unique=True)),
                ('parentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100, unique=True)),
                ('place', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapiapp.CategoryMaster')),
            ],
        ),
    ]
